name: Publish Github Page
on:
  push:
    branches:
      - main
    paths:
      - www/**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # Additional steps to generate documentation in "Documentation" directory
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: ./docs/wiki
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Publish on Github Pages.
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./www
          publish_branch: www
